version: '3.1'

services:
   db:
     container_name: ${CONTAINER_DB_NAME}
     image: mysql:5.7
     restart: always
     volumes:
        - ${DB_PATH}:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   yourls:
     depends_on:
       - db
     container_name: ${CONTAINER_YOURLS_NAME}
     image: yourls
     restart: always
     volumes:
       - ${YOURLS_PATH}:/var/www/html
     environment:
       YOURLS_DB_HOST: ${CONTAINER_DB_NAME}:3306
       YOURLS_DB_NAME: ${MYSQL_DATABASE}
       YOURLS_DB_USER: ${MYSQL_USER}
       YOURLS_DB_PASS: ${MYSQL_PASSWORD}
       YOURLS_SITE: ${YOURLS_SITE}
       VIRTUAL_HOST: ${DOMAIN}
       LETSENCRYPT_HOST: ${DOMAIN}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} 

networks:
    default:
       external:
         name: ${NETWORK}
