version: '3'

services:
   db:
     container_name: ${CONTAINER_DB_NAME}
     image: mariadb:latest
     restart: unless-stopped
     volumes:
        - ${DB_PATH}:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   wordpress:
     depends_on:
       - db
     container_name: ${CONTAINER_YOURLS_NAME}
     image: yourls:fpm-alpine
     restart: unless-stopped
     environment:
       YOURLS_DB_HOST: ${CONTAINER_DB_NAME}:3306
       YOURLS_DB_NAME: ${MYSQL_DATABASE}
       YOURLS_DB_USER: ${MYSQL_USER}
       YOURLS_DB_PASS: ${MYSQL_PASSWORD}
       YOURLS_TABLE_PREFIX: ${YOURLS_TABLE_PREFIX}
       YOURLS_SITE: ${YOURLS_SITE}
       VIRTUAL_HOST: ${YOURLS_SITE}
       LETSENCRYPT_HOST: ${YOURLS_SITE}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} 

networks:
    default:
       external:
         name: ${NETWORK}
